### ISSUE TITLE
--no-collector.bfd options etc are not listed in help text

### ISSUE THREAD

**Issue by stefreak** [tynany/frr_exporter#37]
For collectors that are enabled by default, the option to disable them is not listed in the help text.

For users who are not familiar with kingpin it might be hard for them to figure out the correct option.

I think this is related to https://github.com/alecthomas/kingpin/issues/243

**Comment by tynany** [comment]
That is true. Many Prometheus exporters exhibit the same behaviour (e.g. https://github.com/prometheus/node_exporter), and the expectation is to look at README.md. 

One simple fix is to add something like "to disable, use --no-collector.$collectorName" for all enabled by default collectors. Thoughts? I'm happy to implement something like this if you think it will help. Otherwise, do you have any other suggestions?

**Comment by k0ste** [comment]
In case, where we don't wan't to print all options in help, or for example negate values, we can explicitly enable all services and left for user choice to disable any of collector. This behaviour was used in https://github.com/openstack-exporter/openstack-exporter

**Comment by tynany** [comment]
Added in https://github.com/tynany/frr_exporter/releases/tag/v1.1.0
